# Develop override settings

#url: http://localhost:4000
url: https://localhost:4000


analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
